### PR TITLE
Inline 'site/*' in core

### PR DESCRIPTION
**Pull request by NotMyFault**
Depends on https://github.com/jenkinsci/jenkins/pull/8226 to be backported or included in a `stable-` branch.

Edit: The build fails because my Jenkinsfile change comes from an untrusted revision, not considering the files removed.

Closes https://github.com/jenkins-infra/core-taglibs-report-generator/issues/24

### CODE REVIEW

**Comment by NotMyFault** [comment]
I backported the PR mentioned to 2.414.x, making this PR good to go now.

**Comment by dduportal** [comment]
@NotMyFault I've added you as maintainer of this repository + kicked a scan + rebuild so that you'll the changed Jenkinsfile will be tested

**Review by dduportal — APPROVED** [review]

**Comment by NotMyFault** [comment]
Thanks! I've disabled the job on trusted.ci, activating again on the release day of 2.414.1 to prevent failures.

Oh, you can uninstall dependabot on this repository now, if you like

**Comment by dduportal** [comment]
> Thanks! I've disabled the job on trusted.ci, activating again on the release day of 2.414.1 to prevent failures.
> 
> Oh, you can uninstall dependabot on this repository now, if you like

Thanks! Dependabot does not seem to be set up on this repository (there are no `.github/dependabot.yml` file as far as I can tell)

**Pull request merged**
